### PR TITLE
Progress bar fix for query without results

### PR DESCRIPTION
**Pull request by byapparov**
Fix for issue: https://github.com/rstats-db/bigrquery/issues/171

### CODE REVIEW

**Comment by kahuna-blake** [comment]
Is this going to be merged?

**Comment by byapparov** [comment]
I am also surprised this us still open. Quite a critical issue for non-interactive usage.

**Comment by kahuna-blake** [comment]
Is there currently a way in calling query_exec to disable the progress bar?  I couldn't find it.

**Comment by byapparov** [comment]
@hadley @krlmlr can someone merge this or propose another solution please?

**Comment by hadley** [comment]
I will consider next time I'm working on bigrquery.

**Comment by smrgit** [comment]
any news on this or suggestions for a work-around?

**Comment by riccardopinosio** [comment]
I see, same problem here. It's quite annoying. Wouldn't it be possible to merge byapparov commits and fix the problem?

**Comment by byapparov** [comment]
@hadley it will be great if we could progress with this PR. Are there other maintainers of this package?

it is a shame that package is getting stale.

**Comment by byapparov** [comment]
I am replacing this PR with https://github.com/r-dbi/bigrquery/pull/206 as I need to progress our master forward.

**Pull request closed without merging**
