### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by edgararuiz**
- Adds support for `paste0()`, `cor()` and `cov()`
- Updates NEWS

### CODE REVIEW

**Comment by byapparov** [comment]
Should there be some tests for these features?

**Comment by edgararuiz** [comment]
I couldn't find a test script with that tests other vector functions, so it felt out of scope to me.  The only one I found that was close was a type conversion test: https://github.com/r-dbi/bigrquery/blob/master/tests/testthat/test-sql.R

**Comment by byapparov** [comment]
I think you are pointing to the right place. You should add tests for your code so reviewers could see what you are trying do achieve.

I think for this package tests should be mandatory on PRs as likely few people use it in production. I am not the maintainer and don't want to discourage you. If you need any help with tests let me know.

**Comment by edgararuiz** [comment]
Thanks @byapparov ! You're right, we should have tests for this, and existing SQL vector function customization.

**Comment by hadley** [comment]
@edgararuiz Do you want to merge/rebase?

I don't think it's necessary to test these translations.

**Comment by edgararuiz** [comment]
Ok, I'll fix the conflicts

**Comment by edgararuiz** [comment]
https://github.com/r-dbi/bigrquery/issues/216

**Pull request closed without merging**
