### PR TITLE
Fix no output

### LINKED ISSUE #171: return empty table with no-result query
Hi,

first thanks for creating this amazing package. When I used version 0.3.0, i was able to get an empty table from no result query (Query returned zero records). However, when i used latest version in CRAN 0.4.1, it will return an error: Error: x > 0 is not TRUE

Do you have any suggestions?

Thanks

### PR DESCRIPTION
**Pull request by byapparov**
Fixes #171  - error that happens for queries that return zero rows.

### CODE REVIEW

**Comment by hadley** [comment]
@byapparov is there a reason you closed this PR? It looks good.

**Comment by byapparov** [comment]
@hadley good question. I was doing clean-up on my fork and closed it by mistake. 

Thanks!

**Comment by hadley** [comment]
Can you please add a bullet to NEWS? It should briefly describe the change (starting with name of the function), and crediting yourself with `(@yourname, #issuenumber)`.

Can you please also include `Fixes #xyz` in a commit message (or the text of the PR), then the corresponding issue will be automatically closed when the PR is merged.

**Comment by byapparov** [comment]
Fixes #171

**Comment by byapparov** [comment]
@hadley updated PR body and news.

**Pull request merged**
