### PR TITLE
Rstudio ui connection

### LINKED ISSUE #298: Display bq connection in Rstudio
RStudio 1.1< allows to display sets from the Sql DDBB's connections.

This works with DBI, for example the driver odbc::odbc. 
But not with bigrquery i.e. sets from bigquery don't display in the UI.

More info on the release, [here](https://support.rstudio.com/hc/en-us/articles/115010915687) and [here](https://rstudio.github.io/rstudio-extensions/rstudio-connections.html)

### PR DESCRIPTION
**Pull request by byapparov**
Closes #298

### CODE REVIEW

**Comment by hadley** [comment]
Something is wrong with this PR — it's showing much more in the diff than I'd expect.

**Comment by jennybc** [comment]
> Something is wrong with this PR — it's showing much more in the diff than I'd expect.

@byapparov Would you rebase this branch on master and force push this branch? That should make a smaller, cleaner diff.

**Comment by byapparov** [comment]
@hadley I have used this documentation to implement it: 
https://rstudio.github.io/rstudio-extensions/connections-contract.html

BigQuery objects need to be linked to this contract, which kind of makes sense. 

Let me know if you know of a better way.

**Comment by byapparov** [comment]
@jennybc I don't think I see what you see. When I look at changes in GitHub, all seems relevant to this PR.

**Comment by jennybc** [comment]
Hmm, I was just providing instructions from a general point of view. If the diff looks correct and minimal to you, then so be it.

**Comment by byapparov** [comment]
np, I think it will help if you try to select data from BigQuery in Rstudio to see what this is doing.

**Comment by byapparov** [comment]
I am also trying to get the snippet for connection work based on this: 
https://db.rstudio.com/advanced/snippets/

Do you think it would be useful to default project to what is set in env variable, e.g. `BIGQUERY_PROJECT` ?

**Comment by jennybc** [comment]
Just to say this somewhere @byapparov, there will be another update to bigrquery, at the very least, when I rework its request and response handling to use gargle. We needed to get v1.2.0 out, to get the auth transition rolling, but there will be more chances for your PRs to play out and hopefully be incorporated. We needed to switch the default oauth app, in order to use one from a verified GCP project, with a proper consent screen and privacy policy.

**Comment by byapparov** [comment]
No problems, it is good to see the package moving in all directions.

We can work with the fork for some time.

On the code reviews, I understand you are busy and my expectations are low. It feels like you would benefit from more maintainers to do reviews and approve.

I appreciate all the work that is done here, it's truly amazing )

**Comment by meztez** [comment]
Thanks for the PR, it works fine.

**Comment by hadley** [comment]
Closing in favour of #431

**Pull request closed without merging**
