### PR TITLE
fix geography type parse error

### PR DESCRIPTION
**Pull request by kevinwang09**
Relevant issue: https://github.com/r-dbi/bigrquery/issues/313
Description: Whenever the type of field is GEOGRAPHY, it will fail to be parsed into R. 
Fix: add one extra exception (in src/BqField.cpp) to parse GEOGRAPHY into characters in R. 
For discussion: will it make more sense to parse on all other unexpected field types as characters into R?

Example code
```
library(DBI)
library(bigrquery)

con <- dbConnect(
  drv = bigrquery::bigquery(),
  project = "bigquery-public-data",
  dataset = "covid19_jhu_csse",
  billing = billing ## Whatever your billing is
)

dbListTables(con) ## List all tables in this connection

bigrquery::bq_table_fields("bigquery-public-data.covid19_jhu_csse.summary") ## List field types 

DBI::dbGetQuery(con, "SELECT *
FROM `bigquery-public-data.covid19_jhu_csse.summary`
LIMIT 10;")
```

### CODE REVIEW

**Comment by denironyx** [comment]
Hi @kevinwang09, what's the aim of this issue?? I think it will be a great improvement if R can support the geography data type. Instead of first converting the geography values to strings using the ST_ASTEXT or ST_ASGEOJSON function.

**Comment by hadley** [comment]
I'm with @denironyx here; I'd we should either create high fidelity columns or assume the user will handle it at the SQL level.

**Comment by edzer** [comment]
A candidate native R representation would be an `sfc` column, possibly with `EPSG:4326` as default coordinate reference system, but hopefully with properly set CRS (=datum) information. This would then work with package `sf` and `ggplot2::geom_sf()`.

**Comment by edzer** [comment]
I think both @paleolimbot and @etiennebr have experience with interacting with Big Query GIS from R.

**Comment by denironyx** [comment]
Hi @edzer , 

This was my workaround. 

`### Extracting using the sql and bigrquery
query <- "SELECT * EXCEPT(wkt), ST_ASTEXT(wkt) AS Geometry FROM od_matrix.cartographic_partitions"
harambee_tb <- bq_project_query("harambee-prod", query)
data_haram <- bq_table_download(harambee_tb) %>% 
  sf::st_as_sf(wkt = "Geometry")`

But, they should be a better way to address this issue in the future. I think.

**Pull request closed without merging**
